### ISSUE TITLE
Chrome on Windows - permissions and red color

### ISSUE THREAD

**Issue by tyrusd** [01org/depth-camera-web-demo#1]
Just some things I ran into getting it working on Chrome on Windows [via codepen](https://codepen.io/tind/pen/dNEJmm). Some or all of it may just be my own total ignorance since I've only ever used the Kinect before:

I had to add
`navigator.mediaDevices.getUserMedia({ video: true}); `
to be prompted for permissions. It took a while to realize that was why the labels were all empty and it couldn't find  any devices. 

Then I was getting all red output so I just set the pixel shader to use the red channel for green and blue. And it was really dark so I added a very unsophisticated sort of brightening
`gl_FragColor=vec4(tex.r*2.5, tex.r*2.5, tex.r*2.5,  tex.a)`

I never got the depth contrast effect I see with your beard and glasses in your picture. Maybe I broke something or there is some configuration I need to do. Here's the output of a shoe for reference.
![image](https://cloud.githubusercontent.com/assets/1707787/23223470/c773d180-f8f0-11e6-8012-7a200ac19add.png)

**Comment by astojilj** [comment]
Thanks for trying this out. Yes, the patch fixing this is using getUserMedia with videoKind so the issue is not reproducible.
You could try the live demo from https://01org.github.io/depth-camera-web-demo/.

Dark video is correct - this is a short range camera with the visible range <2m. However, by default (I only guess that is because of not using controls: e.g. [)](http://solsticlipse.com/2015/02/10/intel-real-sense-on-linux-part-2-3d-camera-controls.html)) I'm not seeing anything that is further than 1 meter from camera.
If you'd like to see the full range values and analyze them offline, you could per instance use readPixels or if you'd like to take a screenshot and then color picker to check the values around... render using the shader splitting the 16 bit value to R&G:
fragColor=vec4(mod(tex.r, 0.00390625) * 256.0, ceil(tex.r*256.0) / 256.0, 0, 1.0);
Or, feel free to open another issue for different kind of use cases - I am working on adding more advanced demos here so suggestions are welcome.

My beard is thick (the black area) and I am a bit further than the camera than your shoes is so the contrast is higher. It is still dark. I'm using Razer Stargazer now (SR300) and it looks similar to your screenshot.

> since I've only ever used the Kinect before:
I have a question - it is orthogonal to this issue but related to Chrome Kinect support plans. Did you use Kinect SDK or libfreenect2? Thanks.

**Comment by tyrusd** [comment]
Thanks very much for your response and tips. 

> Did you use Kinect SDK or libfreenect2?

The latest Kinect stuff I played with did the capture using a C# program, not in-browser. It used the Kinect SDK 2.0 to record a series of .ply snapshot "frames". Then it used three.js to loop through them, displayable on the Oculus Rift Dev Kits. [http://laht.info/record-3d-video-with-kinect-v2-and-play-it-back-in-the-browser/](http://laht.info/record-3d-video-with-kinect-v2-and-play-it-back-in-the-browser/)

> I am a bit further than the camera than your shoes is so the contrast is higher

I may have been _too_ close - the contrast is much better when I'm near the end of the detection range. Having something very dark in the image is definitely a help. 

> I am working on adding more advanced demos here so suggestions are welcome

One early goal I have is to just get the 3D data displayed in three,js/aframe and view it in a VR headset in real-time.
Then I'd like to be able to store snippets of the data as a 3D "video", play back and compose them. Then maybe some very basic "holoportation"-style streaming with sockets. 

As far as 2D usage cases go, I'd like to test out some simple shaders to color the image using the depth data. It should be easy but I'm new to shaders.

**Comment by astojilj** [comment]
Thanks.

> One early goal I have is to just get the 3D data displayed in three,js/aframe and view it in a VR headset in real-time.

We are working on point cloud implementation but it is not yet ready. It is based on [this GLES3 code,](https://github.com/IntelRealSense/librealsense/pull/168/files#r103254640) and it might be useful. 

> Then I'd like to be able to store snippets of the data as a 3D "video", play back and compose them. Then maybe some very basic "holoportation"-style streaming with sockets.

Very interesting. To read the full precision data from GPU to CPU (for streaming) you will probably need to try both (WebGL2 required but it is now active by default in Chrome):
1. GetBufferSubDataAsync with transform feedback or
2. asynchronous readPixels.

**Comment by astojilj** [comment]
> > One early goal I have is to just get the 3D data displayed in three,js/aframe and view it in a VR headset in real-time. 
> 
> We are working on point cloud implementation but it is not yet ready. It is based on this GLES3 code, and it might be useful.

PointCloud implementation in WebGL using this code is done, please check it at  [https://github.com/01org/depthcamera-pointcloud-web-demo](https://github.com/01org/depthcamera-pointcloud-web-demo.)

The theory behind it is available at https://w3c.github.io/mediacapture-depth/#synchronizing-depth-and-color-video-rendering

Please note that we dont have the intrinsics and extrinsics implemented in Chrome so they are hardcoded in the  [depthcamera-pointcloud-web-demo](https://github.com/01org/depthcamera-pointcloud-web-demo) for SR300 based cameras.

**Comment by tommasoturchi** [comment]
Hi,
I'm trying to extract the point cloud from the readBuffer, but I get a weird looking point cloud result, where everything seems to be slightly shifted and repeated 3 times. I'm guessing it's the rgba format, but all the attempts of extracting a single r-g-b pixel didn't give me 3 identical r, g, b values. What am I doing wrong?

**Comment by astojilj** [comment]
@tommasoturchi,
Are you referring to the [read back code](https://github.com/01org/depth-camera-web-demo/blob/master/depthdemo.html#L213) in basic depth demo? I assume it is reading depth values as RGBA float, not GL_RED float.
To iterate the values, check the code [here](https://github.com/01org/depth-camera-web-demo/blob/master/depthdemo.html#L221) - it reads every 4th value as values are packed as <red><green><blue><alpha> and we use red, since red, blue and green components in gray are all all having the same value.
