### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by doseguritan** [01org/depth-camera-web-demo#15]
How can I change the background to image instead of video or color?

**Comment by astojilj** [comment]
> How can I change the background to image instead of video or color?

Answer to this, and similar questions, should be covered by the [article following the code](https://01.org/zh/node/28902).
Use image texture instead of video texture [here](https://github.com/01org/depth-camera-web-demo/blob/949c78b894fb77693f8ce9689e6ccca016217095/depth-to-color-sync-render.js#L696).

Since you are interested in background removal, check also [approach using DNN](https://01.org/blogs/astojilj/2018/background-removal-tensorflow.js) with [live demo](https://01org.github.io/depth-camera-web-demo/nn/using-deeplab/index.html).
